[package]
name = "zk_disorder"
version = "0.1.0"
edition = "2024"

[dependencies]
fract = "0.1.2"

rand = "0.9.2"

borsh = { version = "1.0", features = ["derive"]}


serde = { version = "1.0", features = ["derive"] }
